### ISSUE TITLE
文档中添加 《运行环境：centos8+docker20+》 常见错误

### ISSUE THREAD

**Issue by lijinfeng2011** [open-c3/open-c3#221]
运行环境：centos8+docker20+

错误描述：

在服务器安装docker后生成容器时出现出错误

runc: symbol lookup error: runc: undefined symbol: seccomp_api_get

错误原因：

这是缺少头文件或者相关的库之类的问题，是缺少了依赖包，于是安装依赖包

解决办法：

yum install libseccomp-devel

**Comment by v-49** [comment]
yum install libseccomp-devel 后依然存在问题:

[root@Server-190017c5-6ba7-469c-9fdb-84bf99d3bfc7 libseccomp-2.5.2]# yum install libseccomp-devel
Last metadata expiration check: 0:17:02 ago on Mon 30 Sep 2024 03:48:29 PM CST.
Package libseccomp-devel-2.3.3-3.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@Server-190017c5-6ba7-469c-9fdb-84bf99d3bfc7 libseccomp-2.5.2]# runc --version
runc: symbol lookup error: runc: undefined symbol: seccomp_api_get
[root@Server-190017c5-6ba7-469c-9fdb-84bf99d3bfc7 libseccomp-2.5.2]# systemctl restart docker
[root@Server-190017c5-6ba7-469c-9fdb-84bf99d3bfc7 libseccomp-2.5.2]# runc --version
runc: symbol lookup error: runc: undefined symbol: seccomp_api_get

**Comment by v-49** [comment]
具体内容 因为我是linux 8 vault仓库中没有最新的版本；已经安装了 libseccomp-devel，但问题依然存在。这表明系统中的 libseccomp 库和头文件可能不是最新版本，导致 runc 依赖的 seccomp_api_get 符号无法解析。这种情况下，问题很可能与 libseccomp 版本过旧 和 多个版本冲突 有关。当前的 libseccomp 版本是 2.3.3，但这个版本不包含 seccomp_api_get 函数。该函数是从 libseccomp v2.4.0 开始引入的。

**Comment by lijinfeng2011** [comment]
@v-49 你说的这个问题解决了么

**Comment by v-49** [comment]
解决方法是手动下载最新的 2.5X版本的安装包手动安装再重新走流程
