### ISSUE TITLE
审批页面http://oa.cmcloud.org/#/approve打tag的人字段值被截断

### ISSUE THREAD

**Issue by SuJianlin20221012** [open-c3/open-c3#351]
示例：

OPEN-C3审批(CI自动触发)
审批申请人
机器人
申请时间
2022-10-12 16:13:51
审批事由
 发布审批  提交人：weirubo@superatomfin.com;  流水线名: online_dai_main发布; 服务树名称: overseas_finance.uangme_aliyun_new.online_dai_main;  发布版本: release-ina-online-5.9.16; 如需回滚会回滚到版本: release-ina-online-5.9.15  发布环境: online  发现tag的时间: 2022-10-12 15:48:52

 **_打tag的人: weirubo@s_**

**Comment by lijinfeng2011** [comment]
@SuJianlin20221012  这是一个短信消息吗。还是登录到审批平台内容不全？

如果是短信消息的话，短信内容长度有限制，后面的就发不出来了。

**Comment by SuJianlin20221012** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/115622417/195299503-4a6fc528-2771-472a-be85-1f7d976bc9ec.png">

Email中的邮件，跳转到pc端web页面。

**Comment by lijinfeng2011** [comment]
了解了 我们处理一下

**Comment by lijinfeng2011** [comment]
@SuJianlin20221012 我们oa系统的审批内容字段长度太短了，已经加长了。这个问题应该是修复了。
下次看一下是否还有问题。

**Comment by SuJianlin20221012** [comment]
> 

已解决。
