### ISSUE TITLE
[request]: C3后台查看pod日志，希望可以支持关键字过滤功能

### ISSUE THREAD

**Issue by OrionStarGIT** [open-c3/open-c3#744]
类似直接在pod里使用grep查看日志。

另外，如果可以把多个pod的日志支持同时显示到一个console里，那就更加强大了。不用每个pod日志查看或者使用kibana，更高效。

**Comment by lijinfeng2011** [comment]
好的，我们加一下，应该可以

**Comment by lijinfeng2011** [comment]
功能已经开发。 OrionStar Open-C3已经更新。

添加了日志过滤功能。
添加了一次查看deployment中所有pod的日志的功能。

issues我先关闭了，如果有问题在重新打开。
