### ISSUE TITLE
[request]: 资源申请-腾讯云CVM

### ISSUE THREAD

**Issue by yoyo-dy** [open-c3/open-c3#842]
![image](https://github.com/open-c3/open-c3/assets/138742925/dec3aa9c-b6d6-4968-b4c0-8ec2581f1fb8)

1、上图的【项目】、【部门标签】、【产品标签】添加注释说明，并提供新增链接，便于用户直接新增条目
2、【付费方式】仅提供包年包月 OR 按量收费选项，至于后台的接口参数不需要在前端显示。

上述不仅限于腾讯云CVM，建议其他资源申请也参照这种方式

**Comment by lijinfeng2011** [comment]
@leowucn
